openapi: 3.0.0
info:
  description: >
    Dies ist eine Beispiel API, wie wir sie uns auf Seiten der WG Webservices vorstellen würden.
  version: "1.0.2"
  title: WG Webservices API
  contact:
    email: wertgarantie.bifrost@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /productOffers:
    get:
      summary: Retrieve client's product offers for specific object code (device class)
      operationId: getProductOffers
      parameters:
        - name: objectCodeExternal
          in: query
          description: shop's object code of the insurable product (optional)
          required: false
          schema:
            type: string
          examples:
            smartphone:
              value: 'smartphone'
        - name: purchasePrice
          in: query
          description: >-
            purchase price in minor units (cent): filters product offers by
            price range
          required: false
          schema:
            type: integer
            format: int64
          examples:
            sample1:
              value: 80000
              summary: "represents 800.00 EUR"
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            default: 2
          required: false
          description: max number of product offers to send back
        - name: session
          in: header
          description: >-
            current session received from auth call (could be mapped to unique
            agent number)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successfully fetched product offers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductOfferResponse'
components:
  schemas:
    ProductOfferResponse:
      type: object
      properties:
        clientId:
          type: string
          example:
            clientId: "partnershops clientId"
        generalDocuments:
          type: array
          items:
            $ref: '#/components/schemas/Document'
        productOffers:
          type: array
          items:
            $ref: '#/components/schemas/ProductOffer'

    ProductOffer:
      type: object
      properties:
        productId:
          type: string
          format: uuid
          example: "0cec8bba-c66b-4de0-aa92-84f6440a10d3"
        name:
          type: string
          example: "Komplettschutz mit Premium-Option"
        productDocuments:
          type: array
          items:
            $ref: '#/components/schemas/Document'
          example:
            - documentTitle: "GU WG DE KS 0419_PRODUKTINFORMATIONSBLATT.PDF"
              documentType: "IPID"
              documentLink: "https://webservices/documents/GU_WG_DE_KS_0419_PRODUKTINFORMATIONSBLATT.PDF"
        advantages:
          type: array
          items:
            type: string
          example: ["Cyberschutz bei Missbrauch von Online-Accounts und Zahlungsdaten", "Diebstahlschutz", "Keine Selbstbeteiligung im Schadensfall", "Unsachgemäße Handhabung", "Weltweiter Schutz", "Volle Kostenübernahme bei Reparaturen", "..."]
        devices:
          type: array
          items:
            $ref: '#/components/schemas/Device'

    Document:
      type: object
      properties:
        documentTitle:
          type: string
        documentType:
          type: string
        documentLink:
          type: string
      example:
        - documentTitle: "AVB.PDF"
          documentType: "GTCI"
          documentLink: "https://webservices/documents/GAVB.PDF"

    Device:
      type: object
      properties:
        objectCode:
          type: integer
          format: int64
        objectCodeExternal:
          type: string
        maxPriceLimitation:
          type: integer
          format: int64
        intervals:
          type: array
          items:
            $ref: '#/components/schemas/Interval'
      example:
        objectCode: 9025
        objectCodeExternal: "smartphone"
        maxPriceLimitation: 1800
        intervals:
          intervalCode: 1
          description: "monatlich"
          priceRangePremiums:
            - minClose: 0
              maxOpen: 30000
              insurancePremium: 695
            - minClose: 30000
              maxOpen: 80000
              insurancePremium: 995
            - minClose: 80000
              maxOpen: 180000
              insurancePremium: 1295

    Interval:
      type: object
      properties:
        intervalCode:
          type: integer
          format: int64
        description:
          type: string
        priceRangePremiums:
          type: array
          items:
            $ref: '#/components/schemas/PriceRangePremium'
      example:
        intervalCode: 1
        description: "monatlich"
        priceRangePremiums:
          - minClose: 0
            maxOpen: 30000
            insurancePremium: 500
          - minClose: 30000
            maxOpen: 80000
            insurancePremium: 800

    PriceRangePremium:
      type: object
      properties:
        minClose:
          type: integer
          format: int64
        maxOpen:
          type: integer
          format: int64
        insurancePremium:
          type: integer
          format: int64
      example:
        minClose: 0
        maxOpen: 30000
        insurancePremium: 500