openapi: 3.0.0
info:
  description: >
    Dies ist eine Beispiel API, wie wir sie gerne auf Seiten der WG Webservices
    hätten.
  version: '0.0.1'
  title: WG Webservices API
  contact:
    email: wertgarantie.bifrost@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /productOffers:
    get:
      summary: Retrieve client's product offers for specific object code (device class)
      operationId: getProductOffers
      parameters:
        - name: objectCode
          in: query
          description: object code of the insurable shop product (optional)
          required: false
          schema:
            type: string
        - name: purchasePrice
          in: query
          description: >-
            purchase price in minor units (cent): filters product offers by price range
          required: false
          schema:
            type: integer
            format: int64
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            default: 2
          required: false
          description: max number of product offers to send back
        - name: session
          in: header
          description: >-
            current session received from auth call (could be mapped to unique
            agent number)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successfully fetched product offers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductOffer'
components:
  schemas:
    ProductOffer:
      type: object
      properties:
        name:
          type: string
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
    Document:
      type: object
      properties:
        document_title:
          type: string
        document_type:
          type: string
        document_link:
          type: string
    Device:
      type: object
      properties:
        objectCode:
          type: integer
          format: int64
        objectCodeExternal:
          type: string
        maxPriceLimitation:
          type: integer
          format: int64
        intervals:
          type: array
          items:
            $ref: '#/components/schemas/Interval'
    Interval:
      type: object
      properties:
        intervalCode:
          type: integer
          format: int64
        description:
          type: string
        priceRangePremiums:
          type: array
          items:
            $ref: '#/components/schemas/PriceRangePremium'
    PriceRangePremium:
      type: object
      properties:
        minClose:
          type: integer
          format: int64
        maxOpen:
          type: integer
          format: int64
        insurancePremium:
          type: number
          format: double
    GetOffersData:
      type: object
      properties:
        function:
          type: string
        shaping:
          type: string
        API:
          type: string
        session:
          type: string
        agentNr:
          type: string
        objectCode:
          type: integer
          format: int64
        purchasePrice:
          type: number
          format: double
        purchaseDate:
          type: string
          format: date